function image_sources = propagate(P, L, max_order, all_faces, vertices, all_normals, all_centres, max_time)

    % Initialise image source list
    real_entry = struct( ...
        'index', 1, ...
        'parent_index', NaN, ...
        'position', P, ...
        'order', 0, ...
        'created_by', NaN, ...
        'parent_position', NaN(1,3), ...
        'path', [] ...
    );

    image_sources = real_entry;
    max_distance = max_time * 343;
    
    % Start recursive propagation from the real source
    image_sources = recurse( ...
        P, L, ...
        0, NaN, ...
        max_order, ...
        all_faces, vertices, ...
        all_normals, all_centres, ...
        image_sources, ...
        [], ...
        max_distance, ...
        1 ...
    );
end